### ISSUE TITLE
Brute Force Attack

### ISSUE THREAD

**Issue by jonathanmmm** [itemir/apache_2fa#6]
Hi,

I tried to make a pull request, but it somehow doesn't work.

So I ask here.

Is there a some blocking timer after too many attempts of the wrong 6 digit Auth key?

So is there any way to prevent a Brute Force Attack?

I am using apache with mod_evasive, too.

**Comment by itemir** [comment]
There is no specific protection against brute forcing but the concept of TOTP somewhat prevents it . Tokens change every 60 seconds, so in order to brute force, an attacker needs to send 1 million requests (or 500k if you average it out) within 60 seconds. If you have a server that can handle 1m requests a minute, it may be worthwhile to consider an explicit protection.
